name: Publish Images
on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: haya14busa/action-cond@v1
        id: latestTag
        with:
          cond: ${{ github.event.release.target_commitish == 'main' }}
          if_true: "latest"
          if_false: "hotfix"

      - name: Checkout
        uses: actions/checkout@v2

      - name: get-npm-version

        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: guardian-service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/101730247931/locations/global/workloadIdentityPools/hedera-registry-pool/providers/hedera-registry-gh-actions'
          service_account: 'guardian-publisher@hedera-registry.iam.gserviceaccount.com'
          token_format: 'access_token'

      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: logger-service-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./logger-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/logger-service:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/logger-service:latest'

      - name: logger-service
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./logger-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/logger-service:${{ steps.package-version.outputs.current-version}}'

      - name: auth-service-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./auth-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/auth-service:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/auth-service:latest'

      - name: auth-service
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./auth-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/auth-service:${{ steps.package-version.outputs.current-version}}'

      - name: api-gateway-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/api-gateway:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/api-gateway:latest'

      - name: api-gateway
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-gateway/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/api-gateway:${{ steps.package-version.outputs.current-version}}'

      - name: guardian-service-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./guardian-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/guardian-service:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/guardian-service:latest'

      - name: guardian-service
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./guardian-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/guardian-service:${{ steps.package-version.outputs.current-version}}'

      - name: ipfs-client-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ipfs-client/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/ipfs-client:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/ipfs-client:latest'

      - name: ipfs-client
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ipfs-client/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/ipfs-client:${{ steps.package-version.outputs.current-version}}'

      - name: worker-service-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./worker-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/worker-service:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/worker-service:latest'

      - name: worker-service
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./worker-service/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/worker-service:${{ steps.package-version.outputs.current-version}}'

      - name: topic-viewer-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./topic-viewer/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/topic-viewer:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/topic-viewer:latest'

      - name: topic-viewer
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./topic-viewer/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/topic-viewer:${{ steps.package-version.outputs.current-version}}'

      - name: api-docs-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-docs/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/api-docs:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/api-docs:latest'

      - name: api-docs
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./api-docs/Dockerfile
          push: true
          tags: 'gcr.io/hedera-registry/api-docs:${{ steps.package-version.outputs.current-version}}'

      - name: web-proxy-latest
        if: ${{ steps.latestTag.outputs.value == 'latest'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-proxy/Dockerfile.ci
          push: true
          tags: 'gcr.io/hedera-registry/frontend:${{ steps.package-version.outputs.current-version}}, gcr.io/hedera-registry/frontend:latest'

      - name: web-proxy
        if: ${{ steps.latestTag.outputs.value == 'hotfix'}}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-proxy/Dockerfile.ci
          push: true
          tags: 'gcr.io/hedera-registry/frontend:${{ steps.package-version.outputs.current-version}}'
